name: Release unparsd

on:
  push:
    tags:
      - "*"

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: go build .
      - id: changelog
        run: |
          tag=$(git tag --sort version:refname | tail -n 2 | head -n 1)

          if [ "$tag" ]; then
            changelog=$(git log --oneline --no-decorate $tag..HEAD)
          else
            changelog=$(git log --oneline --no-decorate)
          fi

          echo $changelog

          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A' - }"
          changelog=" - ${changelog//$'\r'/'%0D'}"

          echo "changelog=$changelog" >> $GITHUB_OUTPUT
      - uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changelog.outputs.changelog }}
          files: unparsd
